### ISSUE TITLE
在方法上同时加上 重试和熔断后，熔断怎么不作用？

### ISSUE THREAD

**Issue by AjuPrince** [yangzhongke/RuPeng.HystrixCore#3]
在方法上同时加上 重试和熔断后，熔断怎么不作用？
 [HystrixCommand(nameof(Hello1FallBackAsync), MaxRetryTimes = 5, RetryIntervalMilliseconds = 1000, EnableCircuitBreaker = true, ExceptionsAllowedBeforeBreaking = 2, MillisecondsOfBreak = 100)]

![image](https://user-images.githubusercontent.com/16829343/56858778-bdbebd00-69b2-11e9-8c62-f717992a9d13.png)

**Comment by AjuPrince** [comment]
或者说 在满足了 熔断条件后，是不是要等熔断时间完后再次重试呢？

**Comment by yangzhongke** [comment]
sorry，我这里只是一个demo，课程里我也讲了代码的原理，你完全可以根据自己的需要进行定制，欢迎把你的修改提pr上来，我会选择合适的进行merge。
